export const BookData=[
    {
        id : 0,
        book_name : "Harry Potter and the Goblet of Fire" ,
        book_description : "Harry Potter and the Goblet of Fire by J.K. Rowling is the fourth book in the Harry Potter series. It chronicles Harry's fourth year at Hogwarts School of Witchcraft and Wizardry, where he unexpectedly becomes a competitor in the dangerous Triwizard Tournament. Facing daunting tasks alongside rival school champions, Harry uncovers a sinister plot as Lord Voldemort's dark forces gather strength. The novel explores themes of courage, friendship, and the transition from adolescence to adulthood, blending thrilling action with deeper emotional and moral complexities. Rowling's rich storytelling captivates readers, advancing the overarching narrative of Harry's battle against evil.",
        book_url : "https://m.media-amazon.com/images/I/71-CKpDxEYL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "345 pages",
        language : "English",
        author_name : "J.k Rowling" , 
        price : "340" ,
    },
    {
        id : 1,
        book_name : " The Jungle Book" ,
        book_description : "The Jungle Book by Rudyard Kipling is a beloved collection of stories centered around Mowgli, a boy raised by wolves in the Indian jungle. Guided by his animal mentors, Baloo the bear and Bagheera the panther, Mowgli learns the laws of the wild while facing threats from the fearsome tiger Shere Khan. The book includes other memorable tales, such as Rikki-Tikki-Tavi, a mongoose's brave fight against cobras, and Toomai of the Elephants, depicting a young boy's bond with elephants. Kipling's rich storytelling and vivid characters create a magical world that explores themes of nature, survival, and belonging.",
        book_url : "https://m.media-amazon.com/images/I/81EoLfqkRRL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "345 pages",
        language : "English",
        author_name : "Rudyard Kipling " , 
        price : "305" ,
    },
    {
        id :2 ,
        book_name : "Pride And Prejudice",
        book_description : "Pride and Prejudice by Jane Austen is a timeless romantic novel that delves into the life of Elizabeth Bennet, an intelligent and spirited young woman navigating societal expectations in 19th-century England. The story explores themes of love, class, and marriage as Elizabeth encounters the proud and enigmatic Mr. Darcy. Initially, Elizabeth's prejudice and Darcy's pride create tension, but as misunderstandings are clarified, mutual respect and love blossom. Austen's sharp wit and keen social commentary, combined with memorable characters and intricate relationships, have made this novel a cherished classic, highlighting the enduring complexities of human nature and romance.",
        book_url : "https://m.media-amazon.com/images/I/91eKRbuhgaL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "300 pages",
        language : "English",
        author_name : "Jane Austen",
        price : "234",
    },
    {
        id :3 ,
        book_name : "1984",
        book_description : "1984 by George Orwell is a dystopian novel set in a totalitarian society under the constant surveillance of Big Brother. The story follows Winston Smith, a government worker in Oceania, who secretly despises the Party's oppressive regime. As Winston grapples with his thoughts of rebellion and his forbidden love affair with Julia, he discovers the terrifying extent of the Party's control over truth and individuality. Orwell's chilling depiction of a world stripped of freedom and truth serves as a powerful warning about the dangers of totalitarianism, making 1984 a profoundly influential and enduring literary masterpiece.",
        book_url : "https://m.media-amazon.com/images/I/61ZewDE3beL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "250 pages",
        language : "English",
        author_name : "George Orwell",
        price : "250",
    },
 
    {
        id :4 ,
        book_name : "It Ends With Us",
        book_description : "It Ends with Us by Colleen Hoover is a poignant contemporary romance novel that tackles the complexities of love, abuse, and resilience. The story follows Lily Bloom, who, after escaping a troubled past, meets and falls in love with the charismatic neurosurgeon Ryle Kincaid. Their relationship faces challenges as Ryle’s dark side emerges, reminding Lily of her abusive father. When her first love, Atlas Corrigan, reappears, Lily is forced to confront her past and make difficult decisions about her future. Hoover's deeply emotional narrative and well-crafted characters shed light on the cycles of abuse and the strength required to break them.",
        book_url : "https://m.media-amazon.com/images/I/91+lyC7lOdL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "350 pages",
        language : "English",
        author_name : "Colleen Hoover",
        price : "395",
    },
    {
        id :5 ,
        book_name : "To Kill a Mockingbird",
        book_description : " To Kill a Mockingbird by Harper Lee is a profound novel set in the racially charged atmosphere of 1930s Alabama. It follows young Scout Finch, her brother Jem, and their father, Atticus, a principled lawyer. Atticus defends Tom Robinson, a Black man falsely accused of raping a white woman, exposing the children to the harsh realities of prejudice and injustice. Through Scout's eyes, the novel explores themes of morality, empathy, and the loss of innocence. Lee's compelling narrative and richly drawn characters have made this Pulitzer Prize-winning book a timeless classic in American literature, highlighting the enduring struggle for justice and equality.",
        book_url : "https://images-na.ssl-images-amazon.com/images/I/81aY1lxk+9L._AC_UL600_SR600,600_.jpg",
        print_lenght : "300 pages",
        language : "English",
        author_name : "Harper Lee",
        price : "320",
    },
    {
        id :6 ,
        book_name : "Jane Eyre",
        book_description : "Jane Eyre by Charlotte Brontë is a classic novel that follows the life of its titular heroine, an orphan who endures a harsh upbringing to become a governess at Thornfield Hall. There, she meets the enigmatic and brooding Mr. Rochester. As Jane and Rochester develop a deep, complex bond, secrets from his past threaten their happiness. The novel explores themes of love, independence, and social criticism, showcasing Jane's resilience, moral integrity, and quest for self-respect. Brontë's vivid storytelling and rich character development make Jane Eyre a timeless and compelling exploration of a woman's struggle for equality and self-realization.",
        book_url : "https://m.media-amazon.com/images/I/913R4srHS5L._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "280 pages",
        language : "English",
        author_name : "Charlotte Brontë",
        price : "375",
    },
    {
        id :7 ,
        book_name : "Harry Potter and the Chamber of Secrets",
        book_description : "Harry Potter and the Chamber of Secrets by J.K. Rowling is the second installment in the beloved Harry Potter series. It follows Harry's second year at Hogwarts School of Witchcraft and Wizardry, where a series of mysterious attacks on students leads to fears that the legendary Chamber of Secrets has been reopened. With the help of his friends Ron and Hermione, Harry delves into the school's dark history to uncover the truth behind the attacks. The novel combines magical adventure with themes of friendship, bravery, and the power of self-discovery, further enriching the enchanting world Rowling has created.",
        book_url:"https://m.media-amazon.com/images/I/818umIdoruL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "350 pages",
        language : "English",
        author_name : "J.k Rowling",
        price : "350",
    },
    {
        id :8 ,
        book_name : "Good Omens",
        book_description : "Good Omens by Neil Gaiman and Terry Pratchett is a comedic fantasy novel that follows the unlikely partnership between Aziraphale, a fussy angel, and Crowley, a laid-back demon, who team up to prevent the apocalypse. As the end of the world approaches, they must locate the misplaced Antichrist, an 11-year-old boy unaware of his destiny. The story intertwines various eccentric characters, including witch hunters, a prophecy-endowed witch, and the Four Horsemen of the Apocalypse. With sharp wit and satirical humor, Gaiman and Pratchett craft a delightful and thought-provoking narrative about good, evil, and everything in between.",
        book_url : "https://m.media-amazon.com/images/I/51kgNU+LDsL.jpg",
        print_lenght : "300 pages",
        language : "English",
        author_name : "Neil Gaiman",
        price : "380",
    },
    {
        id :9 ,
        book_name : "The Girl On The Train",
        book_description : "The Girl on the Train by Paula Hawkins is a psychological thriller centered around Rachel Watson, an alcoholic who rides the same commuter train daily. She becomes fixated on a seemingly perfect couple, Megan and Scott, whom she observes from the train. When Megan goes missing, Rachel finds herself entangled in the investigation, revealing unsettling truths about Megan’s life and her own. As the narrative unfolds through multiple perspectives, it delves into themes of memory, deception, and the complexity of human relationships. Hawkins' gripping, suspenseful storytelling keeps readers on edge, exploring the darkness lurking beneath everyday lives.",
        book_url : "https://m.media-amazon.com/images/I/61hJEhXPFvL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "300 pages",
        language : "English",
        author_name : "Paula Hawkins",
        price : "299",
    },
    {
        id :10,
        book_name : "the Midnight's Children",
        book_description : "Midnight's Children by Salman Rushdie is a sweeping epic that intertwines the personal and political, following the lives of children born at the exact moment of India's independence on August 15, 1947. The protagonist, Saleem Sinai, discovers he has special telepathic powers linking him to other midnight's children, each with unique abilities. Through Saleem's eyes, the novel explores India's tumultuous history, including its partition and subsequent social upheavals. Rich in magical realism and cultural allegory, Rushdie's narrative is a vibrant, multi-layered tale that captures the essence of a nation grappling with its identity and destiny.",
        book_url : "https://m.media-amazon.com/images/I/814X4A26IOL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "250 pages",
        language : "English",
        author_name : "Dan Gemeinhart",
        price : "200",
    },
    {
        id :11 ,
        book_name : "Charlotte's Web",
        book_description : "Charlotte's Web by E.B. White is a heartwarming children's novel about the friendship between a pig named Wilbur and a wise spider named Charlotte. When Wilbur's life is in danger as he is destined for the slaughterhouse, Charlotte weaves words into her web, proclaiming Wilbur's special qualities to save him. With the help of other farm animals, Charlotte's plan draws human admiration, securing Wilbur's safety. The novel explores themes of friendship, sacrifice, and the cycle of life, with White's gentle storytelling and Garth Williams' charming illustrations making it a beloved classic for readers of all ages.",
        book_url : "https://m.media-amazon.com/images/I/61pJ9xnpojL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "200 pages",
        language : "English",
        author_name : "E.B White",
        price : "412",
    },
    {
        id :12 ,
        book_name : "Harry Potter and the Sorcerer's Stone",
        book_description : "Harry Potter and the Sorcerer's Stone by J.K. Rowling is the first book in the iconic series about a young boy who discovers he is a wizard on his eleventh birthday. Harry Potter, who has lived a difficult life with his abusive aunt and uncle, is invited to attend Hogwarts School of Witchcraft and Wizardry. There, he makes friends, learns about magic, and uncovers the truth about his parents' mysterious deaths. Harry, along with his friends Hermione Granger and Ron Weasley, uncovers the secret of the Sorcerer's Stone and confronts dark forces. The novel is a magical tale of adventure, friendship, and self-discovery.",
        book_url : "https://m.media-amazon.com/images/I/81q77Q39nEL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "300 pages",
        language : "English",
        author_name : "J.K.Rowling",
        price : "299",
    },
    {
        id :13 ,
        book_name : "The Murder of Roger Ackroyd",
        book_description : "The Murder of Roger Ackroyd by Agatha Christie is a classic detective novel featuring the renowned Belgian detective Hercule Poirot. Set in the quaint English village of King's Abbot, the story begins with the tragic death of wealthy industrialist Roger Ackroyd. As Poirot investigates, he uncovers a tangled web of secrets, lies, and motives among the eccentric residents. With its ingenious plot twists and unreliable narrators, Christie's masterpiece keeps readers guessing until the shocking reveal of the murderer's identity. The Murder of Roger Ackroyd is a gripping whodunit that showcases Christie's unparalleled skill in crafting captivating mysteries.",
        book_url : "https://m.media-amazon.com/images/I/81slj2kXK2L._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "350 pages",
        language : "English",
        author_name : "Agatha Christie",
        price : "275",
    },
    {
        id :14 ,
        book_name : "The Book Thief",
        book_description : "The Book Thief by Markus Zusak is a poignant tale set in Nazi Germany, narrated by Death itself. It follows Liesel Meminger, a young girl sent to live with foster parents, as she discovers the power of words and literature amidst the horrors of war. Through stealing books and forming unlikely friendships, Liesel finds solace and courage in storytelling. As the war intensifies, Liesel's small acts of defiance against oppression and her compassionate spirit shine amidst the darkness. Zusak's lyrical prose and memorable characters create a moving narrative that explores the resilience of the human spirit and the enduring impact of kindness.",
        book_url : "https://m.media-amazon.com/images/I/91JGwQlnu7L._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "350 pages",
        language : "English",
        author_name : " Markus Zusak",
        price : "300",
    },
    {
        id :15 ,
        book_name : "The Shining",
        book_description :"The Shining by Stephen King is a chilling psychological horror novel that follows the Torrance family as they become caretakers of the remote Overlook Hotel during the winter. As Jack Torrance, an aspiring writer, grapples with alcoholism and his own inner demons, the hotel's malevolent forces begin to exert their influence, revealing dark secrets and driving Jack towards madness. His son, Danny, possesses psychic abilities known as the shining, which allows him to see the hotel's haunting past and present dangers. King's masterful storytelling and vivid imagery create a tense and atmospheric narrative that explores the fragility of sanity and the power of evil.",
        book_url : "https://m.media-amazon.com/images/I/815Uhzxve5L._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "320 pages",
        language : "English",
        author_name : "Stephen King",
        price : "279",
    },
    {
        id :16 ,
        book_name : "Dracula",
        book_description : "Dracula by Bram Stoker is a Gothic horror novel that introduces the iconic vampire Count Dracula, who leaves his Transylvanian castle to spread terror in Victorian England. The story unfolds through a series of letters, journal entries, and newspaper clippings, as Dracula's insidious influence spreads and a group of determined individuals, led by Professor Abraham Van Helsing, unite to stop him. With its eerie atmosphere, terrifying encounters, and themes of superstition and sexuality, Stoker's masterpiece remains a cornerstone of vampire literature, captivating readers with its timeless tale of good versus evil and the eternal struggle against darkness.",
        book_url : "https://m.media-amazon.com/images/I/41YnrvVY7IL.jpg",
        print_lenght : "260 pages",
        language : "English",
        author_name : "Bram Stoker",
        price : "300",
    },
    {
        id :17 ,
        book_name : "Rebecca",
        book_description : "Rebecca by Daphne du Maurier is a haunting Gothic novel narrated by an unnamed young woman who marries Maxim de Winter, a wealthy widower, and moves to his estate, Manderley. She finds herself haunted by the memory of Maxim's deceased first wife, Rebecca, whose presence still lingers in the house and in the minds of the servants. As secrets about Rebecca's life and death come to light, the new Mrs. de Winter becomes ensnared in a web of jealousy, obsession, and betrayal. Du Maurier's atmospheric prose and gripping suspense make Rebecca a timeless tale of love, loss, and psychological intrigue.",
        book_url : "https://m.media-amazon.com/images/I/91ziTMetVcL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "350 pages",
        language : "English",
        author_name : " Daphne du ",
        price : "384",
    },
    {
        id :18 ,
        book_name : "Lord of the Flies",
        book_description : "Lord of the Flies by William Golding is a compelling allegorical novel that explores the descent into savagery when a group of British boys is stranded on a deserted island during a nuclear war. Initially, they attempt to maintain order and establish a civilized society, electing Ralph as their leader. However, as fear, power struggles, and the lure of the primitive instinct take hold, chaos ensues. The boys split into factions led by Ralph and the ruthless Jack, symbolizing the struggle between civilization and barbarism. Golding's exploration of human nature and the darkness within the human soul remains a thought-provoking classic.",
        book_url : "https://m.media-amazon.com/images/I/81WUAoL-wFL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "375 pages",
        language : "English",
        author_name : "William Golding",
        price : "400",
    },
    {
        id :19 ,
        book_name : "Moby-Dick",
        book_description : "Moby-Dick by Herman Melville is an epic novel that follows the journey of Ishmael, a young sailor, aboard the whaling ship Pequod, captained by the vengeful Ahab. Obsessed with hunting the elusive white whale, Moby Dick, Ahab leads his crew on a perilous quest across the oceans. Along the way, Ishmael reflects on the nature of obsession, fate, and the human condition, while encountering a diverse cast of characters and delving into themes of identity and existentialism. Melville's rich prose, detailed descriptions of whaling life, and philosophical musings have cemented Moby-Dick as a timeless masterpiece of American literature.",
        book_url : "https://m.media-amazon.com/images/I/61+KbxkEhJL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "250 pages",
        language : "English",
        author_name : "Herman Melville",
        price : "370",
    },
    {
        id :20 ,
        book_name : "The Hobbit",
        book_description : "The Hobbit by J.R.R. Tolkien is a captivating fantasy novel that follows Bilbo Baggins, a timid hobbit, on an unexpected adventure. Recruited by the wizard Gandalf and a group of dwarves led by Thorin Oakenshield, Bilbo sets out to reclaim their homeland from the dragon Smaug. Along the way, they encounter trolls, goblins, elves, and other fantastical creatures, as well as the mysterious creature Gollum and his precious ring. As Bilbo discovers his courage and resourcefulness, he becomes an integral part of the quest, ultimately shaping the fate of Middle-earth. Tolkien's enchanting tale is a timeless classic of adventure and heroism.",
        book_url : "https://m.media-amazon.com/images/I/61mjnP-qt6L._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "368 pages",
        language : "English",
        author_name : "J.R.R. Tolkien",
        price : "399",
    },
    {
        id :21 ,
        book_name : "Ikigai",
        book_description : "Ikigai: The Japanese Secret to a Long and Happy Life by Héctor García and Francesc Miralles explores the concept of ikigai, which translates to a reason for being in English. Drawing from Japanese culture, the book delves into finding purpose, passion, and fulfillment in life through the intersection of what one loves, what one is good at, what the world needs, and what one can be paid for. It offers practical advice, inspiring stories, and actionable steps to help readers discover their ikigai and live with greater meaning, balance, and joy, drawing from the wisdom of centenarians in Okinawa, Japan's longevity hotspot.",
        book_url : "https://m.media-amazon.com/images/I/71q1UaeQfcL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "368 pages",
        language : "English",
        author_name : "Héctor García",
        price : "300",
    },
    {
        id :22 ,
        book_name : "Rich Dad Poor Dad",
        book_description : "Rich Dad Poor Dad by Robert T. Kiyosaki is a personal finance classic that challenges conventional wisdom about money and wealth. Through anecdotes from his own life, Kiyosaki contrasts the financial teachings of his poor dad, his biological father, with those of his rich dad, his best friend's father and mentor. The book emphasizes the importance of financial education, asset accumulation, and entrepreneurship for achieving financial independence. Kiyosaki's simple yet powerful lessons on investing, saving, and building passive income streams have inspired millions worldwide to rethink their approach to money and take control of their financial destinies, making it a timeless bestseller.",
        book_url : "https://m.media-amazon.com/images/I/81BE7eeKzAL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "368 pages",
        language : "English",
        author_name : "Robert T. Kiyosaki",
        price : "359",
    },
    {
        id :23 ,
        book_name : "The God of Small Things",
        book_description : "The God of Small Things by Arundhati Roy is a poignant and evocative novel set in Kerala, India, that explores the tragic lives of the twin siblings, Estha and Rahel. Through a non-linear narrative, it reveals how their childhood is shattered by a series of traumatic events, including the forbidden love affair between their mother, Ammu, and Velutha, a man from a lower caste. Roy's lush prose delves into themes of love, social discrimination, and the rigid caste system. The novel's intricate structure and deep emotional resonance won the Booker Prize in 1997, marking it as a modern literary classic.",
        book_url : "https://m.media-amazon.com/images/I/91saO95VziL._AC_UF1000,1000_QL80_.jpg",
        print_lenght : "350 pages",
        language : "English",
        author_name : "Arundhati Roy",
        price : "275",
    },
];
